"""empty message

Revision ID: 0c35ecf674d0
Revises: 9360db754e94
Create Date: 2016-04-30 15:52:30.053974

"""

# revision identifiers, used by Alembic.
revision = '0c35ecf674d0'
down_revision = '9360db754e94'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_constraint('courses_fkey', 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'departments', ['department'], ['department'], onupdate='CASCADE', ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key('courses_fkey', 'courses', 'departments', ['department'], ['department'])
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    ### end Alembic commands ###
